spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysecurity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root